version: '3.1'
services:
  jtg-bot:
    container_name: jtg-bot
    build:
      context: .
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db

  db:
    container_name: postgresql_db
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jtg_db
    volumes:
      - ./psql_storage:/var/lib/postgresql/data
      - ./psql-init:/docker-entrypoint-initdb.d/

  adminer:
    container_name: adminer_web
    image: adminer:4.8.1
    depends_on:
      - db
    ports:
      - 8080:8080
