version: '3.1'
services:
  db:
    container_name: mysql_db
    image: mysql:8.0.27
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jtg_db
      MYSQL_USER: jtg_user
      MYSQL_PASSWORD: jtg_pass
    volumes:
      - ./mysql_storage:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d/

  adminer:
    container_name: adminer_web
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
