version: '3.1'
services:
  db:
    container_name: postgresql_db
    image: postgres:14.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jtg_db
    volumes:
      - ./psql_storage:/var/lib/postgresql/data
      - ./psql-init:/docker-entrypoint-initdb.d/

  adminer:
    container_name: adminer_web
    image: adminer:4.8.1
    depends_on:
      - postgresql_db
    ports:
      - 8080:8080
